export const authActionTypes = {
    REGISTER_REQUEST : 'REGISTER_REQUEST',
    REGISTER_SUCCESS : 'REGISTER_SUCCESS',
    REGISTER_FAILURE : 'REGISTER_FAILURE',

    LOGIN_REQUEST    : 'LOGIN_REQUEST',
    LOGIN_SUCCESS    : 'LOGIN_SUCCESS',
    LOGIN_FAILURE    : 'LOGIN_FAILURE',
    LOGOUT           : 'LOGOUT',
};

export const messageActionTypes = {
    SET_MESSAGE      : 'SET_MESSAGE',
    CLEAR_MESSAGE    : 'CLEAR_MESSAGE'
}

export const postActionTypes = {
    FETCH_POSTS_REQUEST    : 'FETCH_POSTS_REQUEST',
    FETCH_POSTS_SUCCESS    : 'FETCH_POSTS_SUCCESS',
    FETCH_POSTS_FAILURE    : 'FETCH_POSTS_FAILURE',

    ADD_POST_REQUEST     : 'ADD_POST_REQUEST',
    ADD_POST_SUCCESS     : 'ADD_POST_SUCCESS',

    // delete the post
    DELETE_POST_REQUEST      : 'DELETE_POST_REQUEST',
    DELETE_POST_SUCCESS      : 'DELETE_POST_SUCCESS',
    DELETE_POST_FAILURE      : 'DELETE_POST_FAILURE',

    SEND_MESSAGE_REQUEST : 'SEND_MESSAGE_REQUEST',
    SEND_MESSAGE_SUCCESS : 'SEND_MESSAGE_SUCCESS',
    SEND_MESSAGE_FAILURE : 'SEND_MESSAGE_FAILURE',
}

